/**
 * MTM subscription database migrations.
 *
 *   node scripts/migrate.mjs status                         (default; read-only)
 *   node scripts/migrate.mjs apply --dry-run                (read-only plan)
 *   node scripts/migrate.mjs apply --confirm-target DB@HOST [--through NNN]
 *   node scripts/migrate.mjs baseline --through NNN --confirm-target DB@HOST
 *
 * Target: MTM_MIGRATION_DATABASE_URL only — deliberately separate from the
 * application's SUBSCRIPTIONS_DATABASE_URL. Use the provider's DIRECT
 * (non-pooled) endpoint and a migration role; a session advisory lock is held
 * for the run. The same TLS policy as the application applies. Writes need
 * --confirm-target naming the database and host, so a command copied from
 * one environment cannot silently run against another.
 *
 * Never prints the connection string, credentials or row data.
 */
import nextEnv from "@next/env";
import { fileURLToPath } from "node:url";
import pg from "pg";
import { databaseConfig, describeTarget } from "../src/lib/database/policy.mjs";
import { apply, baseline, inspect, loadMigrations } from "./lib/migrations.mjs";

nextEnv.loadEnvConfig(fileURLToPath(new URL("..", import.meta.url)));
const [command = "status", ...rest] = process.argv.slice(2);
const flag = (name) => rest.includes(name);
const option = (name) => {
  const i = rest.indexOf(name);
  return i >= 0 ? rest[i + 1] : undefined;
};

async function main() {
  if (!["status", "apply", "baseline"].includes(command))
    throw new Error(`Unknown command: ${command}`);
  const url = process.env.MTM_MIGRATION_DATABASE_URL;
  if (!url) throw new Error("MTM_MIGRATION_DATABASE_URL is not set");
  const target = describeTarget(url);
  const config = databaseConfig(url, { role: "migration" });
  const through = option("--through");
  if (through !== undefined && !/^\d{3}$/.test(through))
    throw new Error("--through must be a three-digit version");
  const migrations = await loadMigrations();
  const readOnly = command === "status" || flag("--dry-run");
  const client = new pg.Client({
    ...config,
    // Keep any PGOPTIONS (e.g. search_path) and add read-only enforcement.
    ...(readOnly
      ? {
          options: [
            process.env.PGOPTIONS,
            "-c default_transaction_read_only=on",
          ]
            .filter(Boolean)
            .join(" "),
        }
      : {}),
  });
  client.on("error", () => {});
  await client.connect();
  try {
    const state = await inspect(client, migrations);
    console.log(
      `Target: database=${target.database} host=${target.host} port=${target.port} ` +
        `schema=${state.schema} tls=${target.tls ? "verify-full" : "loopback-plain"}`,
    );
    const applied = new Map(state.applied.map((r) => [r.version, r]));
    for (const m of migrations) {
      const row = applied.get(m.version);
      console.log(
        `  ${m.file}  ${row ? `${row.method} ${new Date(row.applied_at).toISOString()}` : "pending"}  sha256:${m.checksum.slice(0, 12)}`,
      );
    }
    for (const p of state.problems) console.log(`  PROBLEM: ${p}`);
    if (readOnly) {
      if (command === "apply")
        console.log(
          `Dry run: would apply ${
            state.pending
              .filter((m) => !through || m.version <= through)
              .map((m) => m.file)
              .join(", ") || "nothing"
          }`,
        );
      if (state.problems.length) process.exitCode = 1;
      return;
    }
    const expected = `${target.database}@${target.host}`;
    if (option("--confirm-target") !== expected)
      throw new Error(
        `Refusing to write: pass --confirm-target ${expected} to confirm this target`,
      );
    if (command === "baseline") {
      if (!through) throw new Error("baseline requires --through NNN");
      await baseline(client, migrations, through);
      console.log(`Baselined through ${through} after object verification`);
    } else {
      const done = await apply(client, migrations, {
        through,
        log: (line) => console.log(`  ${line}`),
      });
      console.log(
        done.length ? `Applied: ${done.join(", ")}` : "Nothing to apply",
      );
    }
  } finally {
    await client.end();
  }
}

main().catch((error) => {
  // Messages are generated by this tooling or PostgreSQL; never the URL.
  console.error(
    `Migration stopped: ${error instanceof Error ? error.message : "unknown error"}`,
  );
  process.exitCode = 1;
});
